### ISSUE TITLE
non-blocking backend

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/lensingwikipedia#143]
@KonceptGeek and I discussed in person a change to the backend that would launch a query as a new thread and also return results incrementally back to the frontend.

This is related to issues #135 and #125

**Comment by KonceptGeek** [comment]
@theq629 @vlad003 , if possible may be we can have a Skype call and discuss various issues related to backend and come up with a plan to fix it and make it more scalable.

**Comment by theq629** [comment]
Sure, if we can find a time that works (my only free time tends to be Vancouver late afternoon).

**Comment by anoopsarkar** [comment]
Any progress on this?

**Comment by vlad003** [comment]
@KonceptGeek @theq629 Sorry, I somehow missed the notification for this. I'd be fine for a Skype call at any time on Monday / Friday, if that works for you guys.

**Comment by theq629** [comment]
I can most days at 3:30-5:30pm Vancouver time, if we can decide a day in advance so I know when to wake up. Not Friday, though.

**Comment by theq629** [comment]
I forgot to say that this Vancouver-time Friday (the 30th), I will also be available in the evening after 7:00pm.

**Comment by KonceptGeek** [comment]
How about Thursday?

Regards,

Jasneet Sabharwal
*AboutMe - http://about.me/jasneetsabharwal
<http://about.me/jasneetsabharwal>*

**Comment by vlad003** [comment]
I've got class 12:30-2:30PM, but I'm free otherwise.

**Comment by theq629** [comment]
Thursday I can in the 3:30-5:30pm time.

**Comment by KonceptGeek** [comment]
So shall we fix it for tomorrow at 3:30pm?

Regards,

Jasneet Sabharwal
*AboutMe - http://about.me/jasneetsabharwal
<http://about.me/jasneetsabharwal>*

**Comment by anoopsarkar** [comment]
@theq629 and @vlad003 perhaps you can join sfu-natlang.slack.com and we can avoid doing this on github issues.

**Comment by theq629** [comment]
Ok, I have joined stack.

**Comment by vlad003** [comment]
What we've discussed on Skype yesterday:

* For each query we get, create a coroutine using gevent
* Make the frontend to poll the backend to check on the status of a query (to check if the query failed, or the whole backend crashed)
  * If backend times out (which it shouldn't since the actual queries are running async), we can assume it crashed
* We need to figure out where the bottleneck truly is (CPU or I/O), and see if gevent is going to be enough or whether we'll have to use multiple processes on the backend (with some sort of loadbalancer in front).
* We need to look into sharding whoosh

**Comment by anoopsarkar** [comment]
Is this issue still alive?

**Comment by vlad003** [comment]
Since I now have uWSGI running the query backend, it's using multiple processes and many gevent workers, so it'll allow many simultaneous queries, and will practically never crash. Each query itself will still block, but none of them seem slow enough for that to be a significant issue (i.e. nothing's timing out); so I think that submitting a query and then polling is overkill, and will only add unnecessary overhead. By the time the frontend will start polling for a response, it would've gotten one from the backend anyways.

What remains to be done is speeding up the processing of responses from Whoosh so that the backend can respond to queries faster; there are several nested for loops that are potentially looping over a large number of items and there should be a way of at least parallelizing those. That's a bit of a different issue than this one, though, so I'll consider this one fixed.
