### ISSUE TITLE
replace flask with falcon

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/lensingwikipedia#182]
Explore whether it is a good idea to replace Flask with Falcon:
 
http://falconframework.org/

Also, Falcon supports Apache htpasswd which might be more lightweight than sqlite.

**Comment by vlad003** [comment]
Falcon looks like it's aiming to solve a different problem than what we're using Flask for. Falcon's good for writing API's but there's no mention of any sort of templating language. The number of requests/second doesn't really matter since Flask is only going to handle a handful of requests per session; once it serves the index.html, it's not really going to get used for much else.

In terms of the htpasswd, anything can technically use Apache htpasswd since it's Apache that's handling it, not the application code. It forces you to manually create usernames and passwords rather than letting people log in with Google, though, and it'll force the user to log in using a pop-up. I'm not sure there's any benefit to using htpasswd over the Google login I wrote.

**Comment by anoopsarkar** [comment]
Sounds good. Closing issue.
